export const groupProjectData = [{
  project: 'AMAzine',
  repoLink: 'https://github.com/AMA-Zine',
  p1: 'Full stack Node, Python, React app that pulls data from various REST API&apos;s to create a web magazine. I was primarily responsible for the endpoints on the back end, building page layouts with React and styling with CSS on the front end.',
  p2: 'Full stack Node, Python, React app that pulls data from various REST API&apos;s to create a web magazine. I was primarily responsible for the endpoints on the back end, building page layouts with React and styling with CSS on the front end.',
  p3: 'Full stack Node, Python, React app that pulls data from various REST API&apos;s to create a web magazine. I was primarily responsible for the endpoints on the back end, building page layouts with React and styling with CSS on the front end.',
  deployLink: 'https://amazine-dev.netlify.app/',
  pictureSource: '../../../public/assets/pagepics/amazine.png',
  pictureAlt: 'Amazine Picture',
},
{
  project: 'Sherlock Stocks',
  repoLink: 'https://github.com/Sherlock-Stocks',
  p1: 'Full stack Node, Python, React app that pulls data from various REST API&apos;s to create a web magazine. I was primarily responsible for the endpoints on the back end, building page layouts with React and styling with CSS on the front end.',
  p2: 'Full stack Node, Python, React app that pulls data from various REST API&apos;s to create a web magazine. I was primarily responsible for the endpoints on the back end, building page layouts with React and styling with CSS on the front end.',
  p3: 'Full stack Node, Python, React app that pulls data from various REST API&apos;s to create a web magazine. I was primarily responsible for the endpoints on the back end, building page layouts with React and styling with CSS on the front end.',
  deployLink: 'https://sherlockstocks.netlify.app/',
  pictureSource: '../../../public/assets/pagepics/sherlockstocks.png',
  pictureAlt: 'Sherlock Stocks Picture',
},
{
  project: 'Truly Trivial',
  repoLink: 'https://github.com/Truly-Trivial',
  p1: 'Full stack Node, Python, React app that pulls data from various REST API&apos;s to create a web magazine. I was primarily responsible for the endpoints on the back end, building page layouts with React and styling with CSS on the front end.',
  p2: 'Full stack Node, Python, React app that pulls data from various REST API&apos;s to create a web magazine. I was primarily responsible for the endpoints on the back end, building page layouts with React and styling with CSS on the front end.',
  p3: 'Full stack Node, Python, React app that pulls data from various REST API&apos;s to create a web magazine. I was primarily responsible for the endpoints on the back end, building page layouts with React and styling with CSS on the front end.',
  deployLink: 'https://fervent-agnesi-b2491a.netlify.app/',
  pictureSource: '../../../public/assets/pagepics/trulytrivial.png',
  pictureAlt: 'Truly Trivial Picture',
},
{
  project: 'Cosmic Checkers',
  repoLink: 'https://github.com/Cosmic-Checkers',
  p1: 'Full stack Node, Python, React app that pulls data from various REST API&apos;s to create a web magazine. I was primarily responsible for the endpoints on the back end, building page layouts with React and styling with CSS on the front end.',
  p2: 'Full stack Node, Python, React app that pulls data from various REST API&apos;s to create a web magazine. I was primarily responsible for the endpoints on the back end, building page layouts with React and styling with CSS on the front end.',
  p3: 'Full stack Node, Python, React app that pulls data from various REST API&apos;s to create a web magazine. I was primarily responsible for the endpoints on the back end, building page layouts with React and styling with CSS on the front end.',
  deployLink: 'https://cosmic-checkers.github.io/Cosmic-Checkers/',
  pictureSource: '../../../public/assets/pagepics/cosmiccheckers.png',
  pictureAlt: 'Cosmic Checkers Picture',
}];

export const soloProjectData = [
  {
    project: 'World Domination',
    repoLink: 'https://github.com/pm-wilson/solo-world-domination',
    p1: 'Full stack Node, Python, React app that pulls data from various REST API&apos;s to create a web magazine. I was primarily responsible for the endpoints on the back end, building page layouts with React and styling with CSS on the front end.',
    p2: 'Full stack Node, Python, React app that pulls data from various REST API&apos;s to create a web magazine. I was primarily responsible for the endpoints on the back end, building page layouts with React and styling with CSS on the front end.',
    p3: 'Full stack Node, Python, React app that pulls data from various REST API&apos;s to create a web magazine. I was primarily responsible for the endpoints on the back end, building page layouts with React and styling with CSS on the front end.',
    deployLink: 'https://pm-wilson.github.io/solo-world-domination/',
    pictureSource: '../../../public/assets/pagepics/worlddomination.png',
    pictureAlt: 'World Domination Picture',
  },
  {
    project: 'Tic Tac Toe',
    repoLink: 'https://github.com/pm-wilson/solo-tic-tac-toe',
    p1: 'Full stack Node, Python, React app that pulls data from various REST API&apos;s to create a web magazine. I was primarily responsible for the endpoints on the back end, building page layouts with React and styling with CSS on the front end.',
    p2: 'Full stack Node, Python, React app that pulls data from various REST API&apos;s to create a web magazine. I was primarily responsible for the endpoints on the back end, building page layouts with React and styling with CSS on the front end.',
    p3: 'Full stack Node, Python, React app that pulls data from various REST API&apos;s to create a web magazine. I was primarily responsible for the endpoints on the back end, building page layouts with React and styling with CSS on the front end.',
    deployLink: 'https://pm-wilson.github.io/solo-tic-tac-toe/',
    pictureSource: '../../../public/assets/pagepics/tictactoe.png',
    pictureAlt: 'Tic Tac Toe Picture',
  }];
